version: '{build}-{branch}'

configuration: Release

before_build:
- nuget restore

build:
  verbosity: minimal
  publish_nuget: true
  project: Yupi.sln


nuget:
  project_feed: true

after_test: 
    - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:"Build/bin/Release/Yupi.Tests.dll --noresult" -filter:"+[Yupi*]*  -[Yupi*]Yupi*.Properties.*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\coverage.xml
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "coverage.xml"
